name: Extractor de Tipos Pokemon

# Configurado para ejecutarse únicamente de forma manual
on:
  workflow_dispatch:

jobs:
  build-and-run:
    # Creamos el entorno virtual basado en la última versión estable de Ubuntu
    runs-on: ubuntu-latest

    steps:
    # 1. Descarga el código del repositorio en el contenedor de Ubuntu
    - name: Descargar código del repositorio
      uses: actions/checkout@v4

    # 2. Configura el entorno de Python
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 3. Prepara el entorno virtual e instala dependencias de scraping
    - name: Instalar dependencias
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install requests beautifulsoup4

    # 4. Ejecuta el script de Python dentro del entorno virtual
    - name: Ejecutar script de Scraping
      run: |
        source venv/bin/activate
        python scrape-types.py
